### ISSUE TITLE
level1 dataset detail

### ISSUE THREAD

**Issue by serotoninpm** [xingdi-eric-yuan/GATA-public#29]
I've been doing a lot of research with your papers. 

I'm very grateful to you for opening up your code like this, but I have one question.

rl.0.2/train_1/difficulty_level_3/tw-cooking-recipe1+take1+cut+open-BNVaijeLTn3jcvneFBY2.z8file is known as level1 in the paper.

when i run this file, i have to cook it like this to get the food. 

However, in the paper it says that you don't need to cook, could you please explain why this is the case?

=======recipe information========
You open the copy of "Cooking: A Modern Approach (3rd Ed.)" and start reading:

Recipe #1
---------
Gather all following ingredients and follow the directions to prepare this tasty
meal.

Ingredients:
  pork chop

Directions:
  slice the pork chop
  roast the pork chop
  prepare meal

**Comment by MarcCote** [comment]
@serotoninpm you are welcome. Thank you for your interest in our work.

While the recipe does asked for a cooked ingredient, since the option +cook wasn't provided, the ingredient you find in the environment should already be cooked correctly. e.g.

![image](https://github.com/xingdi-eric-yuan/GATA-public/assets/660004/e8e9c16b-f170-4a39-98d3-b6ba348f7019)

**Comment by MarcCote** [comment]
I'm glad you find it useful. I'll go ahead and close this issue. Do not hesitate if you have further questions.
